os: linux
dist: xenial

# only one TRAVIS_PYTHON_VERSION
language: python
python:
  - 2.7

# matrix of several CONDA_PYTHON_VERSIONs
env:
  jobs:
    - CONDA_PYTHON_VERSION=2.7  MPL_VERSION=2.2

    - CONDA_PYTHON_VERSION=3.6  MPL_VERSION=3.3
    - CONDA_PYTHON_VERSION=3.7  MPL_VERSION=3.3
    - CONDA_PYTHON_VERSION=3.8  MPL_VERSION=3.3

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    #don't install LaTeX (yet)
    #- texlive-extra-utils
    #- texlive-latex-extra
    - dvipng
    #don't install ROOT yet
    #- root-system

before_install:
  # get miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
    fi
  # install miniconda in batch mode and add to PATH
  - bash $HOME/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # configure conda for batch mode
  - conda config --set always_yes yes --set changeps1 no
  # update conda and show package/environment information
  - conda update -q conda
  - conda info -a

  # install some dependencies with conda and activate environment
  - conda create -q -n kafe_env python=$CONDA_PYTHON_VERSION numpy scipy tk
  - source activate kafe_env

  # upgrade pip to latest version and install iminuit with pip
  - pip install --upgrade pip
  - pip install --upgrade matplotlib==$MPL_VERSION
  - if [[ $CONDA_PYTHON_VERSION == 2.7 ]]; then pip uninstall minuit && pip install iminuit==1.2; else pip install --upgrade iminuit; fi

  # output python version to log
  - python --version

install:
  # install kafe from current directory using pip
  - pip install -e .

script:
  # run unittests with setup.py
  - python setup.py test
